apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: frontend-env
spec:
  refreshInterval: "1m"
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  dataFrom:
    - extract:
        key: counter/env
